#!/usr/bin/env bash

function changed {
    git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

echo 'Checking for changes in package-lock.json...'

if changed 'package-lock.json'; then
    echo "📦 package-lock.json changed. Run npm install to bring your dependencies up to date."
    npm install
fi

echo 'You are up to date :)'
exit 0